### ISSUE TITLE
how to replace to another semantic segmentation network?

### ISSUE THREAD

**Issue by a9311072** [cvlab-epfl/detecting-the-unexpected#11]
Hello @adynathos 

I would like to use this lab to re-write the new network, but I also found there are many dependencies.
Could you share an example to replace the segmentation network?
Thanks a lot. :)

**Comment by adynathos** [comment]
Hello,
Thank you for the interest in my work.

If you'd like to replace the sem-seg in the joint pipeline, here are the functions to change:
[init_semseg](https://github.com/cvlab-epfl/detecting-the-unexpected/blob/e3caa0081633058ba6f34d2e8f8a4ca530bd67fd/src/a05_differences/real_road_data.py#L55)
[tr_apply_semseg](https://github.com/cvlab-epfl/detecting-the-unexpected/blob/e3caa0081633058ba6f34d2e8f8a4ca530bd67fd/src/a05_differences/real_road_data.py#L59) - receives an image and returns the predicted classes

The sem-seg can also be replaced in the evaluation pipline [init_semseg](https://github.com/cvlab-epfl/detecting-the-unexpected/blob/e3caa0081633058ba6f34d2e8f8a4ca530bd67fd/src/a05_differences/E1_article_evaluation.py#L194) but after you do that, it is also important to re-generate the synthesized images (`run_semseg` then `run_gen_image`)

**Comment by qiuqiuzyq** [comment]
Thanks for sharing,
So if I want to replace the GAN and Discrepancy network, just need to change the corresponding function?
`init_gan`      
`init_discrepancy`      
`tr_apply_discrepancy`

**Comment by a9311072** [comment]
thanks
