### ISSUE TITLE
Unable to run Exec_Joint_Pipeline.ipynb

### ISSUE THREAD

**Issue by ShravanthiPatil** [cvlab-epfl/detecting-the-unexpected#14]
Hello,
I am facing issues with running Exec_Joint_Pipeline.ipynb. 

# load the networks
from src.a05_differences.E1_article_evaluation import DiscrepancyJointPipeline
joint_pipeline = DiscrepancyJointPipeline()
joint_pipeline.init_semseg()
joint_pipeline.init_gan()
joint_pipeline.init_discrepancy()

Error: TypeError: exceptions must derive from BaseException

I am using python 3. Could this be a reason? 
Kindly suggest a solution.

Regards,
Shravanthi

**Comment by ShravanthiPatil** [comment]
Solved.

**Comment by LT1st** [comment]
how to handle this?

**Comment by finch185277** [comment]
> how to handle this?

I solve the same problem by downloading weight files [2 GiB] and placing them in the right folder.

ref: https://github.com/cvlab-epfl/detecting-the-unexpected#trained-weights
