### ISSUE TITLE
Why are buses and trucks detected as anomalies?

### ISSUE THREAD

**Issue by sikla** [cvlab-epfl/detecting-the-unexpected#18]
Hey,
when i run the pipeline with the given weights on the cityscapes dataset it seems that all buses and trucks are detected as anomalies. Why is that?
Help would be appreciated. Thanks in advance!
![image](https://user-images.githubusercontent.com/97105330/168613104-9ce8b5ca-9451-43fb-9fb8-f729f32f4467.png)

**Comment by adynathos** [comment]
Buses and trucks in Cityscapes are rare compared to cars or pedestrians.

When generating synthetic anomalies we choose an object and switch its
class to a random one. The probabilities of choosing each replacement class
are equal.
So in the synthetic training set, truck and bus instances are more often
coming from this substitution (and are anomalies) than from usual
occurrence in the Cityscapes dataset.
Hence the detector may learn that bus/truck class is correlated with being
an anomaly.

The fix would be to choose synthetic replacement class probability
according to the frequency of this class in Cityscapes.

**Comment by sikla** [comment]
Thanks a lot for your answer!
