### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by RamyaRaghuraman** [cvlab-epfl/detecting-the-unexpected#3]
Hi @adynathos,

CUDA runs out of memory at 
"eval_obj.run_semseg(dset, b_show=False)"

Is there any way to clear the cache memory in CUDA?

**Comment by adynathos** [comment]
In 020db5cb63d869db50c2f6fd40c41189143f0f4d I add the ability to:
- change the batch size of the pipeline: `joint_pipeline.set_batch_size(2)`
- run in half-precision with the [apex](https://github.com/nvidia/apex) library: `joint_pipeline.init_apex_optimization()`

Hopefully these help with the GPU memory.

**Comment by Olive-fcj** [comment]
Is there any way to limit the gpu id?

**Comment by adynathos** [comment]
@Olive-fcj 
Control which GPU is used with `CUDA_VISIBLE_DEVICES=n`, where `n` is the id of the GPU starting from 0.

https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/
